# Generated by Django 5.2.4 on 2025-07-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('SST', models.IntegerField()),
                ('ENG', models.IntegerField()),
                ('SCI', models.IntegerField()),
                ('MTC', models.IntegerField()),
                ('AGG', models.IntegerField(null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SST_GRADE', models.CharField(max_length=30)),
                ('SCI_GRADE', models.CharField(max_length=30)),
                ('ENG_GRADE', models.CharField(max_length=15)),
                ('MTC_GRADE', models.CharField(max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ple_app.student_model')),
            ],
        ),
    ]
