# Generated by Django 5.2.4 on 2025-07-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ple_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='TOTAL',
            field=models.IntegerField(null=True),
        ),
    ]
