# Generated by Django 5.2.4 on 2025-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ple_app', '0002_student_model_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='Grade',
            field=models.IntegerField(null=True),
        ),
    ]
