# Generated by Django 5.2.2 on 2025-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ple_app', '0003_student_model_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='Student_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
